/* Created on 15.12.2024 */
package org.javerland.jdbcsheets;

import java.io.File;
import java.sql.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * @author juraj.pacolt
 */
class JdbcSheetsStatement implements Statement {

    final JdbcSheetsConnection connection;
    final File file;
    final String id;
    Map<String, JdbcSheetsResultSet> resultSetMap = new LinkedHashMap<>();
    private JdbcSheetsResultSet lastResultSet;
    private boolean closed = false;

    public JdbcSheetsStatement(JdbcSheetsConnection connection, File file) {
        this.connection = connection;
        this.file = file;
        this.id = UUID.randomUUID().toString();
    }

    public String getId() {
        return id;
    }

    protected File getFile() {
        return file;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ensureOpen();
        JdbcSheetsResultSet rs = new JdbcSheetsResultSet(connection, this, sql);
        resultSetMap.put(rs.getId(), rs);
        lastResultSet = rs;
        return rs;
    }

    protected void closeResultSet(String resultSetId) {
        resultSetMap.remove(resultSetId);
        if (lastResultSet != null && lastResultSet.getId().equals(resultSetId)) {
            lastResultSet = null;
        }
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void close() throws SQLException {
        for (JdbcSheetsResultSet rs : resultSetMap.values()) {
            rs.close();
        }
        resultSetMap.clear();
        lastResultSet = null;
        closed = true;
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        // ignore
    }

    @Override
    public int getMaxRows() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        // ignore
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        // ignore
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        // ignore
    }

    @Override
    public void cancel() throws SQLException {
        // ignore
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        // ignore
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        // ignore
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        // ignore
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return lastResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return -1;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return lastResultSet != null;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        // ignore
    }

    @Override
    public int getFetchDirection() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        // ignore
    }

    @Override
    public int getFetchSize() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public int getResultSetType() throws SQLException {
        return 0;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        // ignore
    }

    @Override
    public void clearBatch() throws SQLException {
        // ignore
    }

    @Override
    public int[] executeBatch() throws SQLException {
        // ignore
        return new int[0];
    }

    @Override
    public Connection getConnection() throws SQLException {
        return connection;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return getMoreResults();
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return execute(sql);
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        // ignore
        return 0;
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        // ignore
    }

    @Override
    public boolean isPoolable() throws SQLException {
        // ignore
        return false;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        // ignore
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        // ignore
        return false;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    private void ensureOpen() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed.");
        }
    }
}
